version: '3'
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ID=node1
      - NODE_ADDRESS=http://node1:8080
      - PEERS=http://node2:8081
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - redis
  node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - NODE_ID=node2
      - NODE_ADDRESS=http://node2:8081
      - PEERS=http://node1:8080
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"